### PR TITLE
Fix IBM SE verifier

### PR DESCRIPTION
**Pull request by lmilleri**
Added the missing se_parse_hdr.py file to the IBM SE verifier code

### CODE REVIEW

**Comment by lmilleri** [comment]
@ajayvic please review

**Review by ajayvic — APPROVED** [review]
LGTM, Thanks Leonardo for the fix..

**Comment by spotlesstofu** [comment]
Please rebase so the build can succeed

**Review by gauravkuredhat — APPROVED** [review]
Changes Look good.

**Pull request merged**
