### PR TITLE
openshift: Only use one image for trustee

### PR DESCRIPTION
**Pull request by fidencio**
In the meeting hold Today by Leonardo, we discussed that only one image could be shipped, as long as we build the project using the stubs, and then install the Intel RPM for runtime usage.

This is the first (almost blind?) attempt to do so.

### CODE REVIEW

**Comment by beraldoleal** [comment]
Failing because is blocked by this PR:

https://github.com/openshift/trustee/pull/22

**Review by beraldoleal — APPROVED** [review]
Since this is not GA, LGTM.

**Review by jensfr — APPROVED** [review]
LGTM

**Comment by cpmeadors** [comment]
lgtm

**Comment by fidencio** [comment]
@cpmeadors, @jensfr, in order to avoid rebases due to the changes in the konflux files, could you get it merged after the tests pass?

I don't have the needed powers to push it myself.

**Pull request merged**
